### ISSUE TITLE
Color scheme

### ISSUE THREAD

**Issue by hdev1** [tmfd/origami-desktop#1]
Hello eli. I think we should decide on a color scheme.
I have a suggestion: let's use gradients. Sort of like this: http://eagle.phys.utk.edu/guidry/android/figs/modNavDrawer.png

So, we need to decide on one color scheme, these are my suggestions:
1: http://uigradients.com#TealLove and http://uigradients.com#NeonLife
I think these two are good. I think TealLove is a bit better.
2: http://uigradients.com#Amethyst
This one also looks great, and is very easy on the eye.
3: http://uigradients.com#EndlessRiver
Imo, a better version of 1.
4: http://uigradients.com#Timber
The best way to describe this one is "bold". I think it's pretty good too

Which of these is the best? Do you have any other suggestions?

**Comment by elisaado** [comment]
Gradiants are the new thing, look at Instagram :laughing: 

I love the teal color, just like my Profile picture

I like the teal love one, but it's pretty bright, that's why I like 3 more than 1 :+1: 

I think we should go with 3.

,
Eli
